[project]
name = "uncertainty-in-ml"
version = "1.0.0"
description = "S&P 500 Forecasting and Risk Quantification using Gaussian Processes."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gpytorch>=1.15.2",
    "jupyter>=1.1.1",
    "kaggle>=2.2.0",
    "matplotlib>=3.10.9",
    "optuna>=4.9.0",
    "pandas>=3.0.3",
    "pre-commit>=4.6.0",
    "ruff>=0.15.14",
    "scikit-learn>=1.8.0",
    "tensorboard>=2.20.0",
    "torch>=2.12.0",
    "ty>=0.0.46",
    "yfinance>=0.2.40",
]

[tool.ruff]
line-length = 80
